config/routes.rb
Rails.application.routes.draw do
   
  root 'static/page#welcome'
  namespace :content do
    resources :entries
  end  

end

app/models/content.rb
module Content
  def self.table_name_prefix
    'content_'
  end
end

app/models/content/entry.rb
class Content::Entry < ActiveRecord::Base
  
  def self.get_entries_search(params)
    entries = Content::Entry.order("created_at DESC")    
    return entries
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/content/base_controller.rb
class Content::BaseController < ApplicationController
  layout 'infocontact/infocontact'
end

app/controllers/content/entries_controller.rb
class Content::EntriesController < Content::BaseController
  before_action :set_content_entry, only: [:show, :edit, :update, :destroy]

  # GET /content/entries
  # GET /content/entries.json
  def index
    # @content_entries = Content::Entry.all    
    @content_entries = Content::Entry.order("title DESC").page params[:page]    
  end

  # GET /content/entries/1
  # GET /content/entries/1.json
  def show
    redirect_to edit_content_entry_path(@content_entry)    
  end

  # GET /content/entries/new
  def new
    @content_entry = Content::Entry.new
  end

  # GET /content/entries/1/edit
  def edit
  end

  # POST /content/entries
  # POST /content/entries.json
  def create
    @content_entry = Content::Entry.new(content_entry_params)

    respond_to do |format|
      if @content_entry.save
        format.html { redirect_to @content_entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @content_entry }
      else
        format.html { render :new }
        format.json { render json: @content_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content/entries/1
  # PATCH/PUT /content/entries/1.json
  def update
    respond_to do |format|
      if @content_entry.update(content_entry_params)
        format.html { redirect_to @content_entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @content_entry }
      else
        format.html { render :edit }
        format.json { render json: @content_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content/entries/1
  # DELETE /content/entries/1.json
  def destroy
    @content_entry.destroy
    respond_to do |format|
      format.html { redirect_to content_entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_entry
      @content_entry = Content::Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_entry_params
      params.require(:content_entry).permit(:title, :slug, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content/entries_helper.rb
module Content::EntriesHelper
end

app/views/content/entries/_form.html.erb
<%= form_for(@content_entry) do |f| %>
  <% if @content_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content_entry.errors.count, "error") %> prohibited this content_entry from being saved:</h2>

      <ul>
      <% @content_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="main-content">
    <div class="field title-field">
      <%= f.text_field :title, class: 'top-bars', placeholder: "Enter title here", maxlength: 69 %>
    </div>    
    <div class="field">
      <%= f.text_area :content, :class => "tinymce", :rows => 25, :cols => 10 %>
      <script>      
      //<![CDATA[
      tinyMCE.init({
          "selector":"textarea.tinymce",
          "toolbar_location":"top",
          "toolbar_align":"left",
          "statusbar_location":"bottom",
          "buttons3_add":"tablecontrols,fullscreen,code",
          "plugins":"uploadimage,textcolor,lists,charmap,searchreplace,code,media,table,fullscreen,link,insertdatetime,contextmenu,visualblocks,paste,advlist,image,importcss,pagebreak,autosave","insertdate_dateformat":"%Y-%m-%d",
          toolbar: "bold,italic,underline,|,bullist,numlist,outdent,indent,|,undo,redo,|,pastetext,pasteword,selectall,|,uploadimage",
          relative_urls: false,
          remove_script_host: false,
          document_base_url: (!window.location.origin ? window.location.protocol + "//" + window.location.host : window.location.origin) + "/",
          setup : function(ed) {
            ed.on('change', function(e) {
              $('#post_preview').disable(true);
            });
          }});
      //]]>
      </script>
    </div>
  </div>  
  <div class="right-sidebar">
    <div class="div-box">
      <% if(action_name == "edit" || action_name == "update") %>
      <% button_label = "Update" %>
      <% else %>
      <% button_label = "Create" %>
      <% end %>
      <h3 style="padding-bottom: 25px;">Publish <button type="button" id="post_preview" class="btn submit-button" style="margin-left:15px;" disabled>View</button> <%= f.submit button_label, :class => 'btn btn-primary submit-button'%></h3>    
    <div class="field">
      <%= f.label :created_at %><br>
      <%= f.date_select(:created_at) %>
   </div>
  </div>

    <div class="div-box">
      <h3>Options</h3>        
    <div class="field">
      <%= f.label :display_statesite, "Display on State Sites" %><br>
      <%= f.check_box :display_statesite %>
    </div>        
  </div>

  </div>  
<% end %>
<script>
  // Add button click in
  $("#post_preview").bind("click", function(evt, ui) {
    evt.preventDefault();
    prefix = get_prefix();
    slug = $("#content_entry_slug").val();
    if(slug == "index"){
      slug = "";
    }
    //window.open(prefix + slug + "/?post_preview=true", '_blank');
    return false;
  });

  // Disable function
  jQuery.fn.extend({
      disable: function(state) {
          return this.each(function() {
              this.disabled = state;
          });
      }
  });

  // Set action
  window.action_name = "<%= action_name %>"
  if(action_name == "edit" || action_name == "update"){
    $('#post_preview').disable(false);
  }

  // Set display statesites
  if($("#content_entry_display_statesite").is(':checked')){
    window.display_statesite = true;
  }
  else{
    window.display_statesite = false;
  }

  $("#slug").html($("#content_entry_slug").val());
  $(".pageheader").hide();
  $(document).ready(function() {
  $('#slug').editable({
    type: 'text',
    title: 'Enter username',
    success: function(response, newValue) {
        $("#content_entry_slug").val(newValue);
    }
  });
});
</script>

app/views/content/entries/edit.html.erb
<h2>Editing Entry <%= link_to 'Add New', new_content_entry_path,{:class=>"new-button"} %></h2>
<% provide(:title, "Entry: #{@content_entry.title}") %>
<%= render 'form' %>

app/views/content/entries/index.html.erb
<h2>Entries <%= link_to 'Add New', new_content_entry_path,{:class=>"new-button"} %></h2>

<div class="toggle-entry-search">
	<span class="iconfa-search"></span> Click Here to Toggle Search
</div><br>

<div class="entry-search">
  <%= form_tag(content_entries_path, method: :get) do %>       
    <div class="field search-buttons">
      <%= submit_tag( "Search" ) %> | <%= link_to "Clear search parameters", content_entries_path %>
    </div>
  <% end %>
</div>
<%= paginate @content_entries %>
<h4 class="widgettitle"><%= page_entries_info(@content_entries) %></h4>
<div class="widgetcontent">
<table class="table table-hover table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Content</th>
      <th>ImageURL</th>
      <th>Order</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @content_entries.each do |content_entry| %>     
      <tr>
        <td><%= link_to content_entry.title, edit_content_entry_path(content_entry) %></td>
        <td><%= content_entry.title %></td>
        <td><%= content_entry.slug %></td>        
        <td><%= content_entry.image_url %></td>
        <td><%= content_entry.order %></td>        
        <td><%= link_to 'Edit', edit_content_entry_path(content_entry) %></td>
        <td><%= link_to 'Destroy', content_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<%= paginate @content_entries %>

<script>
  $(".pageheader").hide();
  $(".toggle-entry-search").click(function() {
  	$(".entry-search").toggle();
  });
  
  $(".entry-search").hide();

  
  //show the program search if the user has searched
  <% if params[:commit] == 'Search' %>
	$(".entry-search").show();
  <% end %>
</script>

app/views/content/entries/new.html.erb
<h2>New Entry</h2>
<% provide(:title, "Entry: New") %>
<%= render 'form' %>

app/views/content/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @content_entry.type.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @content_entry.status.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @content_entry.user.username %>
</p>

<p>
  <strong>State:</strong>
  <%= @content_entry.state.name %>
</p>

<p>
  <strong>Sector:</strong>
  <%= @content_entry.sector.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @content_entry.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @content_entry.slug %>
</p>

<p>
  <strong>Content:</strong>
  <%= simple_format @content_entry.content %>
</p>

<% if @content_entry.temp_keywords.present? %>
<p>
  <strong>Keywords:</strong>
  <%= @content_entry.temp_keywords %>
</p>
<% end %>

<p>
  <strong>Image url:</strong>
  <%= @content_entry.image_url %>
</p>

<p>
  <strong>Featured:</strong>
  <%= @content_entry.featured %>
</p>

<p>
  <strong>Order:</strong>
  <%= @content_entry.order %>
</p>

<p>
  <strong>Display statesite:</strong>
  <%= @content_entry.display_statesite %>
</p>

<%= link_to 'Edit', edit_content_entry_path(@content_entry) %> |
<%= link_to 'Back', content_entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '#' %></li>
              <li><%= link_to "Help",    '#' %></li>
              <li><%= link_to "Sign in", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/infocontact/_black_action_container.html.erb
   <div class="row-fluid">   
        <div class="widgetbox box-inverse">                        
        <div class="headtitle">
        	<% if content_for?(:black_action_container_actions) %>
            <div class="btn-group">
                <button data-toggle="dropdown" class="btn dropdown-toggle">Action <span class="caret"></span></button>
                <ul class="dropdown-menu">
              		<%= content_for :black_action_container_actions %>
                </ul>
            </div>
            <% end %>
            <h4 class="widgettitle">
	        <% if content_for?(:black_action_container_title) %>
              <%= content_for :black_action_container_title %>
            <% end %>
            </h4>
        </div>
        <div class="widgetcontent">
            <% if content_for?(:black_action_container_content) %>
              <%= content_for :black_action_container_content %>
            <% end %>
        </div><!--widgetcontent-->
        </div><!--widgetbox-->        
	</div>

app/views/layouts/infocontact/_breadcrumbs.html.erb
<% if(@account_current_user) %>
<ul class="breadcrumbs">
    <li><a href="/"><i class="iconfa-home"></i></a> <span class="separator"></span></li>
    <li><%= params[:controller].split('/')[1].capitalize %>  <span class="separator"></span> 
    	<%= params[:controller].split('/').last.humanize.capitalize %>  <span class="separator"></span> 
    	<%= params[:action].capitalize %></li>
    <li style="padding-left: 10px;">| &nbsp;&nbsp;&nbsp; <b>Quick links:</b> </li>


    
    <li class="right"><%= link_to '<i class="iconfa-signout"></i> Logout'.html_safe, account_logout_path %></li>
    <li class="right"><%= link_to '<i class="iconfa-user"></i> My Account'.html_safe, edit_account_user_path(@account_current_user) %></li>
    <li class="right" style="display:none;">
        <a href="" data-toggle="dropdown" class="dropdown-toggle"><i class="iconfa-book"></i> History</a>
        <ul class="dropdown-menu pull-right">
            <% if false %>
                <% @page_history.reverse.each_with_index do |url, index| %>
                  <li><%= link_to "#{index+1}. #{url[0,100]}", url %></li>
                <% end %>
            <% end %>
        </ul>
    </li>
</ul>
<% end %>

app/views/layouts/infocontact/_custom_jquery.html.erb
	<script type="text/javascript">
    $(document).ready(function() {
      
      //$.noConflict();
		
		$(document).ready(function(){
			
			// dropdown in leftmenu
			$('.leftmenu .dropdown > a').click(function(){
				if(!$(this).next().is(':visible'))
					$(this).next().slideDown('fast');
				else
					$(this).next().slideUp('fast');	
				return false;
			});
			
			
			if($.uniform) 
			   $('input:checkbox, input:radio, .uniform-file').uniform();
				
			if($('.widgettitle .close').length > 0) {
				  $('.widgettitle .close').click(function(){
							 $(this).parents('.widgetbox').fadeOut(function(){
										$(this).remove();
							 });
				  });
			}
			
			
	
	
   // add menu bar for phones and tablet
   jQuery('<div class="topbar"><a class="barmenu">'+
		    '</a><div class="chatmenu"></a></div>').insertBefore('.mainwrapper');
	
	jQuery('.topbar .barmenu').click(function() {
		  
		  var lwidth = '260px';
		  if(jQuery(window).width() < 340) {
					 lwidth = '260px';
		  }
		  
		  if(!jQuery(this).hasClass('open')) {
					 jQuery('.rightpanel, .headerinner, .topbar').css({marginLeft: lwidth},'fast');
					 jQuery('.logo, .leftpanel').css({marginLeft: 0},'fast');
					 jQuery(this).addClass('open');
		  } else {
					 jQuery('.rightpanel, .headerinner, .topbar').css({marginLeft: 0},'fast');
					 jQuery('.logo, .leftpanel').css({marginLeft: '-'+lwidth},'fast');
					 jQuery(this).removeClass('open');
		  }
	});
	
	jQuery('.topbar .chatmenu').click(function(){
		if(!jQuery('.onlineuserpanel').is(':visible')) {
			jQuery('.onlineuserpanel,#chatwindows').show();
			jQuery('.topbar .chatmenu').css({right: '210px'});
		} else {
			jQuery('.onlineuserpanel, #chatwindows').hide();
			jQuery('.topbar .chatmenu').css({right: '10px'});
		}
	});
	
	// show/hide left menu
	jQuery(window).resize(function() {
		  if(jQuery('.topbar').is(':visible')) {
				if(jQuery('.barmenu').hasClass('open')) {
						 jQuery('.rightpanel, .headerinner').css({marginLeft: '260px'});
						 jQuery('.logo, .leftpanel').css({marginLeft: 0});
				} else {
						 jQuery('.rightpanel, .headerinner').css({marginLeft: 0});
						 jQuery('.logo, .leftpanel').css({marginLeft: '-260px'});
				}
		  } else {
				jQuery('.rightpanel, .headerinner').css({marginLeft: '260px'});
				jQuery('.logo, .leftpanel').css({marginLeft: 0});
		  }
   });
	
	// dropdown menu for profile image
	jQuery('.userloggedinfo img').click(function(){
		  if(jQuery(window).width() < 480) {
					 var dm = jQuery('.userloggedinfo .userinfo');
					 if(dm.is(':visible')) {
								dm.hide();
					 } else {
								dm.show();
					 }
		  }
   });
	
			/*
			// change skin color
			$('.skin-color a').click(function(){ return false; });
			$('.skin-color a').hover(function(){
				var s = $(this).attr('href');
				if($('#skinstyle').length > 0) {
					if(s!='default') {
						$('#skinstyle').attr('href','css/style.'+s+'.css');	
						$.cookie('skin-color', s, { path: '/' });
					} else {
						$('#skinstyle').remove();
						$.cookie("skin-color", '', { path: '/' });
					}
				} else {
					if(s!='default') {
						$('head').append('<link id="skinstyle" rel="stylesheet" href="css/style.'+s+'.css" type="text/css" />');
						$.cookie("skin-color", s, { path: '/' });
					}
				}
				return false;
			});
			
			// load selected skin color from cookie
			if($.cookie('skin-color')) {
				var c = $.cookie('skin-color');
				if(c) {
					$('head').append('<link id="skinstyle" rel="stylesheet" href="css/style.'+c+'.css" type="text/css" />');
					$.cookie("skin-color", c, { path: '/' });
				}
			}
			*/
			
			// expand/collapse boxes
			if($('.minimize').length > 0) {
				  
				  $('.minimize').click(function(){
							 if(!$(this).hasClass('collapsed')) {
										$(this).addClass('collapsed');
										$(this).html("&#43;");
										$(this).parents('.widgetbox')
												      .css({marginBottom: '20px'})
														.find('.widgetcontent')
														.hide();
							 } else {
										$(this).removeClass('collapsed');
										$(this).html("&#8211;");
										$(this).parents('.widgetbox')
												      .css({marginBottom: '0'})
														.find('.widgetcontent')
														.show();
							 }
							 return false;
				  });
					  
			}
			
			// fixed right panel
			var winSize = $(window).height();
			if($('.rightpanel').height() < winSize) {
				$('.rightpanel').height(winSize);
			}
			
			
			// if facebook like chat is enabled
			if($.cookie('enable-chat')) {
				
				$('body').addClass('chatenabled');
				$.get('ajax/chat.html',function(data){
					$('body').append(data);
				});
				
			} else {
				
				if($('.chatmenu').length > 0) {
					$('.chatmenu').remove();
				}
				
			}
			
		});
		      

    
        
        //datepicker
        $('#datepicker').datepicker();
        $( ".datepicker" ).datepicker({});
        
        // tabbed widget
        $('.tabbedwidget').tabs();
        
        
    });
</script>

app/views/layouts/infocontact/_flash_messages.html.erb
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/infocontact/_footer.html.erb
<div class="footer">
	
    <div class="footer-left">
        <span>&copy; <%= Time.new.year %> -  This is test project. All Rights Reserved.</span>
    </div>
    <div class="footer-right">
       
    </div>
    <br/><br/><%= debug(params) if Rails.env.development? %>
</div><!--footer-->

app/views/layouts/infocontact/_header.html.erb
<div class="header">
        <div class="logo">
          <a href="/" style="color:white;text-decoration:none;font-family:RobotoThin;"><h1>The Silo</h1></a>  
        </div>
        <div class="headerinner">
            <ul class="headmenu">
                <li class="odd">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="count">4</span>
                        <span class="head-icon head-message"></span>
                        <span class="headmenu-label">Messages</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-header">Messages</li>
                        <li><a href=""><span class="icon-envelope"></span> New message from <strong>Jack</strong> <small class="muted"> - 19 hours ago</small></a></li>
                        <li><a href=""><span class="icon-envelope"></span> New message from <strong>Daniel</strong> <small class="muted"> - 2 days ago</small></a></li>
                        <li><a href=""><span class="icon-envelope"></span> New message from <strong>Jane</strong> <small class="muted"> - 3 days ago</small></a></li>
                        <li><a href=""><span class="icon-envelope"></span> New message from <strong>Tanya</strong> <small class="muted"> - 1 week ago</small></a></li>
                        <li><a href=""><span class="icon-envelope"></span> New message from <strong>Lee</strong> <small class="muted"> - 1 week ago</small></a></li>
                        <li class="viewmore"><a href="messages.html">View More Messages</a></li>
                    </ul>
                </li>
                
                <li>
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#">
                    <span class="count">10</span>
                    <span class="head-icon head-users"></span>
                    <span class="headmenu-label">New Users</span>
                    </a>
                    <ul class="dropdown-menu newusers">
                        <li class="nav-header">New Users</li>
                        <li>
                            <a href="">
                                <img src="/assets/shamcey/photos/thumb1.png" alt="" class="userthumb" />
                                <strong>Draniem Daamul</strong>
                                <small>April 20, 2013</small>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/assets/shamcey/photos/thumb2.png" alt="" class="userthumb" />
                                <strong>Shamcey Sindilmaca</strong>
                                <small>April 19, 2013</small>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/assets/shamcey/photos/thumb3.png" alt="" class="userthumb" />
                                <strong>Nusja Paul Nawancali</strong>
                                <small>April 19, 2013</small>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/assets/shamcey/photos/thumb4.png" alt="" class="userthumb" />
                                <strong>Rose Cerona</strong>
                                <small>April 18, 2013</small>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img src="/assets/shamcey/photos/thumb5.png" alt="" class="userthumb" />
                                <strong>John Doe</strong>
                                <small>April 16, 2013</small>
                            </a>
                        </li>
                    </ul>
                </li>
                
                <li class="odd">
                    <a class="dropdown-toggle" data-toggle="dropdown" data-target="#">
                    <span class="count">1</span>
                    <span class="head-icon head-bar"></span>
                    <span class="headmenu-label">Statistics</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-header">Statistics</li>
                        <li><a href=""><span class="icon-align-left"></span> New Reports from <strong>Products</strong> <small class="muted"> - 19 hours ago</small></a></li>
                        <li><a href=""><span class="icon-align-left"></span> New Statistics from <strong>Users</strong> <small class="muted"> - 2 days ago</small></a></li>
                        <li><a href=""><span class="icon-align-left"></span> New Statistics from <strong>Comments</strong> <small class="muted"> - 3 days ago</small></a></li>
                        <li><a href=""><span class="icon-align-left"></span> Most Popular in <strong>Products</strong> <small class="muted"> - 1 week ago</small></a></li>
                        <li><a href=""><span class="icon-align-left"></span> Most Viewed in <strong>Blog</strong> <small class="muted"> - 1 week ago</small></a></li>
                        <li class="viewmore"><a href="charts.html">View More Statistics</a></li>
                    </ul>
                </li>
                <li class="right">
                    <div class="userloggedinfo">
                        <img src="/assets/shamcey/photos/thumb1.png" alt="" />
                        <div class="userinfo">
                        	
                 
                        	
                            <% if account_current_user %>	
                            <h5><%= account_current_user.username %> <small>- <%= account_current_user.role.name %></small></h5>
                            <ul>
                                <li><a href="editprofile.html">Edit Profile</a></li>
                                <li><a href="">Account Settings</a></li>
                                <li><%= link_to "Logout", account_logout_path %></li>
                            </ul>
                            <% end %>
                        </div>
                    </div>
                </li>
            </ul><!--headmenu-->
        </div>
    </div>

app/views/layouts/infocontact/_leftpanel.html.erb
    <div class="leftpanel">
        
        <div class="leftmenu">        
            <ul class="nav nav-tabs nav-stacked">
            	<li class="nav-header">Navigation</li>
                <li class="<%= "active" if params[:controller].include?("static/pages") %>"><%= link_to '<span class="iconfa-laptop"></span> Home'.html_safe, root_path %></li>               
                <li class="dropdown <%= "active" if params[:controller].include?('content')%>"><%= link_to '<span class="iconfa-pencil"></span> Content entries'.html_safe, '' %>
                	<ul <%= "style=display:block;" if params[:controller].include?("content")%>>
                        <li <%= 'class=active' if params[:controller].include?("entr") %>><%= link_to 'Entries', new_content_entry_path %></li>                    	
                    </ul>
                </li>               
                
        </div><!--leftmenu-->
        
    </div><!-- leftpanel -->

app/views/layouts/infocontact/_modal_placeholder.html.erb
<div aria-hidden="false" aria-labelledby="myModalLabel" data-backdrop="static" role="dialog" tabindex="-1" class="modal hide fade in" id="myModal">
</div><!--#myModal-->

app/views/layouts/infocontact/_page_header.html.erb
<div class="pageheader">
    <!--<form action="results.html" method="post" class="searchbar">
        <input type="text" name="keyword" placeholder="To search type and hit enter..." />
    </form>-->
    
    <% if params[:controller].include?('admin/static')%>
    <a href="<%= root_path %>">
	    <div class="pageicon"><span class="iconfa-laptop"></span></div>
	    <div class="pagetitle">
	        <h5>Namespace</h5>
	        <h1>Dashboard</h1>
	    </div>
    </a>
    <% end %>
    
    <% if params[:controller].include?('account')%>
    <a href="<%= account_users_path %>">
	    <div class="pageicon"><span class="iconfa-user"></span></div>
	    <div class="pagetitle">
	        <h5>Namespace</h5>
	        <h1>Account</h1>
	    </div>
    </a>
    <% end %>
    
    <% if params[:controller].include?('vendor')%>
    <a href="#">
	    <div class="pageicon"><span class="iconfa-briefcase"></span></div>
	    <div class="pagetitle">
	        <h5>Namespace</h5>
	        <h1>Vendor</h1>
	    </div>
    </a>
    <% end %>
    
    
</div><!--pageheader-->

app/views/layouts/infocontact/_rightpanel.html.erb
    <div class="rightpanel">
        
        
        
        <%= render 'layouts/infocontact/breadcrumbs' %>
        
        
        <%= render 'layouts/infocontact/flash_messages' %>
        
        <div class="maincontent">
            <div class="maincontentinner">
            	
            	<%= yield %>
  
                <%= render 'layouts/infocontact/footer' %>               
            </div><!--maincontentinner-->
        </div><!--maincontent-->        
    </div><!--rightpanel-->

app/views/layouts/infocontact/infocontact.erb
<!DOCTYPE html>
<html>
	<headtinymce-jquery
	
	
	>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<!--<meta name="viewport" content="width=device-width, initial-scale=1.0" />-->
		<title><%= yield(:title).empty? ? "The alextest" : yield(:title) %></title>
		<%= stylesheet_link_tag    "infocontact/application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "infocontact/application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<script src="http://code.highcharts.com/highcharts.js"></script>
		<script src="http://code.highcharts.com/modules/exporting.js"></script>
		<link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet"/>
		<script src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap-editable/js/bootstrap-editable.min.js"></script>
	</head>

	<body>

		<div id="mainwrapper" class="mainwrapper">

			<%#= render 'layouts/shamcey/header' %>
			
			<%= render 'layouts/infocontact/leftpanel' %>
			<%= render 'layouts/infocontact/rightpanel' %>

		</div><!--mainwrapper-->

		<%= render 'layouts/infocontact/custom_jquery' %>

		<%= render 'layouts/infocontact/modal_placeholder' %>

	</body>
</html>